#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : TeSS Platform Documentation  # The title of the book. Will be placed in the left navbar.
author                      : Phil Reed, Munazah Andrabi, Finn Bacall, Kenneth Rioja, Martin Voigt, Valentin Ryckert, Oliver Knodel, Carole Goble (OSCARS mTeSS-X project)
copyright                   : "2025-2026"  # Copyright year to be placed in the footer
logo                        : images/logo.png  # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ElixirTeSS/docs  # Online location of your book
  path_to_book: .  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: _static/favicon.png
  use_issues_button: true
  use_repository_button: true

# Generate anchor links for headings down to h3, so we can do eg [API](#api)
sphinx:
  config:
    myst_heading_anchors: 3
